on:
  push:
  
jobs:
  github-example-tags:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
    
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
        
      - name: Test
        run: echo ${{ steps.tag.outputs.new_tag }}
