on:
  push:
  
jobs:
  github-example-tags:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
